export const API_BASE_URL = process.env.REACT_APP_API_URL || 'http://localhost:8080/api';

export const USER_ROLES = {
  ADMIN: 'ROLE_ADMIN',
  COLLECTOR: 'ROLE_COLLECTOR',
  USER: 'ROLE_USER'
};

export const REQUEST_STATUS = {
  PENDING: 'PENDING',
  SCHEDULED: 'SCHEDULED',
  COLLECTED: 'COLLECTED',
  CANCELLED: 'CANCELLED'
};

export const ASSIGNMENT_STATUS = {
  AVAILABLE: 'AVAILABLE',
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED'
};